
export const icWalkFirst = require('../assets/images/Rectangle2608/Rectangle2608.png')
export const icWalkSecond = require('../assets/images/Rectangle2609/Rectangle2609.png')
export const icWalkThird = require('../assets/images/Rectangle2610/Rectangle2610.png')
export const icSplashLogo = require('../assets/images/SplashLogo/SplashLogo.png')
export const icCarMech = require('../assets/images/CarMech/CarMech.png')
export const icHome = require('../assets/images/home/home.png')
export const icLink = require('../assets/images/link/link.png')
export const icFaceId = require('../assets/images/faceId/faceId.png')
export const icCollage = require('../assets/images/collage/collage.png')
export const icProfile = require('../assets/images/person/person.png')
export const icNotificationBell = require('../assets/images/notificationBell/notificationBell.png')
export const icSignUpBg = require('../assets/images/signUpBg/signUpBg.png')
export const icPlane = require('../assets/images/plane/plane.png')
